import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Profile from "@/components/profile";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-8">
          <div className="max-w-3xl w-full">
            <Profile />

            <div className="my-8 border-b border-gray-600" />

            <Navbar />
          </div>
        </main>
      </body>
    </html>
  );
}
